### ISSUE TITLE
RangeError: Trying to access beyond buffer length

### ISSUE THREAD

**Issue by maddin77** [JJJ4n/node-mta-query#2]
**Server:** `91.121.170.212:22006`

``` bash
maddin@songbird:~/node-mta-query$ mocha --reporter spec test.js


  query
    1) should return info


  0 passing (44ms)
  1 failing

  1) query should return info:
     Uncaught RangeError: Trying to access beyond buffer length
      at checkOffset (buffer.js:582:11)
      at Buffer.readUInt8 (buffer.js:588:5)
      at Socket.<anonymous> (/home/maddin/node-mta-query/mta-query.js:110:42)
      at Socket.emit (events.js:98:17)
      at UDP.onMessage (dgram.js:440:8)
```

**Comment by maddin77** [comment]
Aktuelle Infos findet man auf deren Seite ([pcpgang.net](http://pcpgang.net/index.php?option=com_content&view=article&id=4&Itemid=7)) bzw direkt hier: [http://pcpgang.net/monitor/mini.php](http://pcpgang.net/monitor/mini.php)
